// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLanguageData_(arg1) {
  return window['go']['main']['Application']['GetLanguageData_'](arg1);
}
